services:
  app:
    image: ghcr.io/chaixdev/grocerun:${GROCERUN_VERSION:-latest}
    container_name: grocerun
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: file:/app/data/prod.db
      OIDC_CLIENT_ID: ${OIDC_CLIENT_ID}
      OIDC_CLIENT_SECRET: ${OIDC_CLIENT_SECRET}
      OIDC_AUDIENCE: ${OIDC_CLIENT_ID}
      HOSTNAME: 0.0.0.0
    env_file:
      - .env
    volumes:
      - grocerun_data:/app/data

volumes:
  grocerun_data:
