/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StoresRouteImport } from './routes/stores'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ListsRouteImport } from './routes/lists'
import { Route as HouseholdsRouteImport } from './routes/households'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StoresStoreIdRouteImport } from './routes/stores_.$storeId'
import { Route as ListsListIdRouteImport } from './routes/lists_.$listId'
import { Route as StoresStoreIdSettingsRouteImport } from './routes/stores_.$storeId.settings'

const StoresRoute = StoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ListsRoute = ListsRouteImport.update({
  id: '/lists',
  path: '/lists',
  getParentRoute: () => rootRouteImport,
} as any)
const HouseholdsRoute = HouseholdsRouteImport.update({
  id: '/households',
  path: '/households',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresStoreIdRoute = StoresStoreIdRouteImport.update({
  id: '/stores_/$storeId',
  path: '/stores/$storeId',
  getParentRoute: () => rootRouteImport,
} as any)
const ListsListIdRoute = ListsListIdRouteImport.update({
  id: '/lists_/$listId',
  path: '/lists/$listId',
  getParentRoute: () => rootRouteImport,
} as any)
const StoresStoreIdSettingsRoute = StoresStoreIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => StoresStoreIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/households': typeof HouseholdsRoute
  '/lists': typeof ListsRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/stores': typeof StoresRoute
  '/lists/$listId': typeof ListsListIdRoute
  '/stores/$storeId': typeof StoresStoreIdRouteWithChildren
  '/stores/$storeId/settings': typeof StoresStoreIdSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/households': typeof HouseholdsRoute
  '/lists': typeof ListsRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/stores': typeof StoresRoute
  '/lists/$listId': typeof ListsListIdRoute
  '/stores/$storeId': typeof StoresStoreIdRouteWithChildren
  '/stores/$storeId/settings': typeof StoresStoreIdSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/households': typeof HouseholdsRoute
  '/lists': typeof ListsRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/stores': typeof StoresRoute
  '/lists_/$listId': typeof ListsListIdRoute
  '/stores_/$storeId': typeof StoresStoreIdRouteWithChildren
  '/stores_/$storeId/settings': typeof StoresStoreIdSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/households'
    | '/lists'
    | '/login'
    | '/settings'
    | '/stores'
    | '/lists/$listId'
    | '/stores/$storeId'
    | '/stores/$storeId/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/households'
    | '/lists'
    | '/login'
    | '/settings'
    | '/stores'
    | '/lists/$listId'
    | '/stores/$storeId'
    | '/stores/$storeId/settings'
  id:
    | '__root__'
    | '/'
    | '/households'
    | '/lists'
    | '/login'
    | '/settings'
    | '/stores'
    | '/lists_/$listId'
    | '/stores_/$storeId'
    | '/stores_/$storeId/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HouseholdsRoute: typeof HouseholdsRoute
  ListsRoute: typeof ListsRoute
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
  StoresRoute: typeof StoresRoute
  ListsListIdRoute: typeof ListsListIdRoute
  StoresStoreIdRoute: typeof StoresStoreIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stores': {
      id: '/stores'
      path: '/stores'
      fullPath: '/stores'
      preLoaderRoute: typeof StoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lists': {
      id: '/lists'
      path: '/lists'
      fullPath: '/lists'
      preLoaderRoute: typeof ListsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/households': {
      id: '/households'
      path: '/households'
      fullPath: '/households'
      preLoaderRoute: typeof HouseholdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores_/$storeId': {
      id: '/stores_/$storeId'
      path: '/stores/$storeId'
      fullPath: '/stores/$storeId'
      preLoaderRoute: typeof StoresStoreIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lists_/$listId': {
      id: '/lists_/$listId'
      path: '/lists/$listId'
      fullPath: '/lists/$listId'
      preLoaderRoute: typeof ListsListIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stores_/$storeId/settings': {
      id: '/stores_/$storeId/settings'
      path: '/settings'
      fullPath: '/stores/$storeId/settings'
      preLoaderRoute: typeof StoresStoreIdSettingsRouteImport
      parentRoute: typeof StoresStoreIdRoute
    }
  }
}

interface StoresStoreIdRouteChildren {
  StoresStoreIdSettingsRoute: typeof StoresStoreIdSettingsRoute
}

const StoresStoreIdRouteChildren: StoresStoreIdRouteChildren = {
  StoresStoreIdSettingsRoute: StoresStoreIdSettingsRoute,
}

const StoresStoreIdRouteWithChildren = StoresStoreIdRoute._addFileChildren(
  StoresStoreIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HouseholdsRoute: HouseholdsRoute,
  ListsRoute: ListsRoute,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
  StoresRoute: StoresRoute,
  ListsListIdRoute: ListsListIdRoute,
  StoresStoreIdRoute: StoresStoreIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
